# Generated by Django 5.2.1 on 2025-06-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
    ]
