# Generated by Django 5.2.1 on 2025-06-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_player_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
