# Generated by Django 5.2.1 on 2025-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_player_final_price_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
