# Generated by Django 5.2.1 on 2025-06-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.group'),
        ),
    ]
