# Generated by Django 5.2.1 on 2025-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team_images/'),
            preserve_default=False,
        ),
    ]
